Auto_testing:
  stage: Auto_testing
  tags:
    - rhel
  except:
    - pushes
  only:
    - triggers
    - web
  dependencies: 
    - Search_issueformlh
    - Down_targz
  script:
    - ./scripts/start_attests.sh
    - ./scripts/gen_json_from_readme.sh genattestresult 
#  after_script:
#    - ./scripts/start_attests_afterscript.sh
  artifacts:
    paths:
      - $CI_JOB_NAME.stderr
      - $CI_JOB_NAME.json
      - $CI_JOB_NAME.rfc822
      - numtests.txt
      - cucumber.xml
#      - Temp/$AT_PROJECT/target/site/
      - Temp/$AT_PROJECT/target/site/allure-maven-plugin/data/*.json
      - testrun_log.log  
    when: always  
    reports:
      junit: cucumber.xml
    expire_in: 1 week

